### ISSUE TITLE
No longer required after Retype v1.8.0

### ISSUE THREAD

**Issue by geoffreymcgill** [supremegamers/wiki#7]
Once Retype [`v1.8.0`](https://github.com/retypeapp/retype/releases) is released, the following work-around would not be required:

https://github.com/supremegamers/wiki/blob/48f9b79e0a9b98040917e57ff2b3fef5427c9275/.github/workflows/main.yml#L47-L54

You will be able to add `/edit/` to the end of the `edit.repo` config and Retype will not modify that URL:

https://github.com/supremegamers/wiki/blob/48f9b79e0a9b98040917e57ff2b3fef5427c9275/retype.json#L13-L16

The `edit` config would be revised to the following:

```json
  "edit": {
    "repo": "https://github.com/supremegamers/wiki/edit"
  },
```

Your existing configuration will continue to work after the `v1.8.0`, but performance of the Action will improve if you make the above revisions. I will try and send a PR too, once `v1.8.0` has been released. 

Hope this helps.

**Comment by axonasif** [comment]
Thanks!

**Comment by geoffreymcgill** [comment]
PR #9 submitted with a fix for this issue and some other minor revisions. 

Also upgraded the project configuration to use the new `retype.yml` file format, instead of `retype.json`. Exactly the same build result, just cleaner now.

Hope this helps.
